export { default as Home } from './Home/Home';
export { default as Footer } from './Footer/Footer';
// export { default as Add } from './Add/Add';
export { default as Login } from './Auth/Login/Login';
export { default as Register } from './Auth/Register/Register';
// export { default as Success } from './Success/Success';
export { default as NotFound } from './NotFound/NotFound';
export { default as ProductPage } from './ProductPage/ProductPage';
export { default as Cart } from './Cart/Cart';
export { default as ChatCustomer} from './ChatCustomer/ChatCustomer';
export { default as CustomerHome} from './CustomerHome/CustomerHome';
